services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: disaster_db
      MYSQL_USER: disaster_user
      MYSQL_PASSWORD: disaster_password
      MYSQL_ROOT_PASSWORD: disaster_root_password
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysqldata:
