import { useEffect, useState } from 'react';
import { getIncidentDetail } from '../services/mockApi';

export default function IncidentDetails({ incidentId }) {
  const [incident, setIncident] = useState(null); const [error, setError] = useState('');
  useEffect(() => { setIncident(null); setError(''); getIncidentDetail(incidentId).then(setIncident).catch(() => setError('Unable to load incident details.')); }, [incidentId]);
  if (error) return <p className="rounded-lg bg-error-container/30 p-3 text-sm text-error">{error}</p>;
  if (!incident) return <p className="rounded-lg bg-surface-container p-4 text-sm text-outline">Loading incident details…</p>;
  return <section className="rounded-xl border border-outline-variant/40 bg-surface-container-low p-4"><p className="font-mono text-xs text-primary">{incident.id} · P{incident.priority}</p><h2 className="mt-1 text-lg font-bold">{incident.type}</h2><p className="mt-2 text-sm text-on-surface-variant">{incident.description || 'No additional description supplied.'}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-outline">Origin / channel</dt><dd className="font-bold">{incident.receivedVia === 'offline-sync' ? 'Mesh sync' : 'Direct SOS'}</dd></div><div><dt className="text-outline">Received</dt><dd className="font-bold">{new Date(incident.timestamp).toLocaleString()}</dd></div><div><dt className="text-outline">Location</dt><dd className="font-bold">{incident.location.lat.toFixed(4)}, {incident.location.lng.toFixed(4)}</dd></div><div><dt className="text-outline">Contact</dt><dd className="font-bold">{incident.contact || 'Not supplied'}</dd></div><div><dt className="text-outline">Affected people</dt><dd className="font-bold">{incident.victimCount}</dd></div><div><dt className="text-outline">Status</dt><dd className="font-bold capitalize">{incident.status}</dd></div></dl>{incident.mediaReferences?.length > 0 && <p className="mt-4 text-sm text-secondary">Attachments: {incident.mediaReferences.join(', ')}</p>}{incident.duplicateReportLinks?.length > 0 && <p className="mt-2 text-sm text-outline">Related reports: {incident.duplicateReportLinks.join(', ')}</p>}</section>;
}
